
project:
  title: The proof assigment
  description: Have fun with coding
  version: 0.0.1
  rapydo: 0.6.3

variables:
  env:
    AUTH_SERVICE: mongo
    MONGO_DATABASE: proof
    FRONTEND_ENABLE: 1
    TOKEN_DEFAULT_TTL: 86400 # 1 day in seconds
    REACT_DEFAULT_PORT: 5000
    EMAIL_ACTIVATION_SUBJECT: "Proof: Verify your email"
    REGISTRATION_NOTIFICATIONS: 1
    SMTP_NOREPLY: "Proof Media Inc. <no-reply@proofmedia.io>"
    SMTP_HOST: smtp.gmail.com
    SMTP_PORT: 465
    #######################
    # PLEASE CUSTOMIZE FROM HERE BELOW
    ## email setup - you can create a gmail account for that
    SMTP_USERNAME: youraccount@gmail.com
    SMTP_PASSWORD: youraccountdifficultpassword
    SMTP_ADMIN: someotheraccount@gmail.com
    # ^ this is the email admin account that receives a notification
    # every time a user tries to register
    #######################
